INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'bok choy', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'snake beans', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'sorrel leaves', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'rocket leaves', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'drumstick', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'cherry tomatoes', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'kaffir lime', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'plantain', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'turnip', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'sweet potatoes', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'round gourd', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'ridge gourd', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'pimiento', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'spinach', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'onion', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'mustard leaves', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'mushroom', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'radish', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'coriander powder', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'chives', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'galangal', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'tulsi', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'sage', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'rosemary', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'yellow chillies', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'oregano', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'nasturtium', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'salt', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'mustard powder', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'paprika', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'mint leaves', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'marjoram', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'lemongrass', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'red chilli', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'saffron', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'dried fenugreek leaves', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'amaranth', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'flour', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'muesli', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'oats', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'jowar', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'brown rice', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'arborio rice', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'water chestnut flour', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'barnyard millet', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'tapioca', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'semolina', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'finger millet', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'puffed rice', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'buckwheat', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'kidney beans', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'whole bengal gram', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'green gram', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'all purpose flour', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'beef', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'grass fed chicken', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'free range chicken', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'organic chicken', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'turkey', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'skinned chicken', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'pork', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'partridge', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'meat stock', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'keema', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'mutton liver', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'ham', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'kidney meat', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'crab', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'chicken stock', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'chicken liver', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'chicken', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'chops', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'gruyere cheese', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'gouda cheese', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'feta cheese', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'milk', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'brie cheese', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'cream cheese', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'ricotta cheese', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'parmesan cheese', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'blue cheese', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'cheddar cheese', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'mascarpone cheese', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'cream', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'provolone cheese', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'mozzarella cheese', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'khoya', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'hung curd', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'yogurt', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'cottage cheese', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'cranberry', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'kiwi', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'blueberries', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'mango', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'watermelon', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'tomato', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'strawberry', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'water chestnut', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'papaya', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'orange rind', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'orange', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'olives', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'pear', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'sultana', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'mulberry', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'lychee', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'lemon juice', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'lemon rind', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'shrimp', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'tuna fish', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'shellfish', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'shark', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'hilsa', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'sardines', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'salmon', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'prawns', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'pomfret', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'perch', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'pearl spot', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'mussels', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'mullet', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'squids', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'haddock', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'flounder', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'fish stock', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'fish', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'brown sugar', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'sugar candy', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'icing sugar', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'honey', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'jaggery', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'golden syrup', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'sugar', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'castor sugar', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'caramel', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'cane sugar', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'canola oil', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'chia seeds', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'hazelnut', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'pine nuts', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'mustard oil', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'sunflower seeds', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'sesame oil', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'pistachio', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'olive oil', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'mustard seeds', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'poppy seeds', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'sesame seeds', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'peanuts', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'chironji', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'cashew nuts', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'blanched almonds', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'almonds', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'walnuts', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'almond milk', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'red wine vinegar', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'red wine', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'margarine', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'soy milk', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'white wine', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'yeast', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'white pepper', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'rice vinegar', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'sea salt', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'hoisin sauce', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'malt vinegar', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'chocolate chips', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'quinoa', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'rice flour', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'polenta', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'oyster sauce', DEFAULT, null);
INSERT INTO  ingredient_tag ("id", "name", "create_time", "update_time") VALUES (DEFAULT, 'guchchi', DEFAULT, null);