INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '4 Tbsp (57 gr) butter', 1, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '4 Tbsp (57 gr) butter', 2, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '4 Tbsp (57 gr) butter', 3, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '4 Tbsp (57 gr) butter', 4, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '4 Tbsp (57 gr) butter', 5, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '4 Tbsp (57 gr) butter', 6, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '2 large eggs', 1, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '2 large eggs', 2, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '2 large eggs', 3, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '2 large eggs', 4, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '2 large eggs', 5, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '2 large eggs', 6, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '2 yogurt containers granulated sugar', 1, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '2 yogurt containers granulated sugar', 2, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '2 yogurt containers granulated sugar', 3, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '2 yogurt containers granulated sugar', 4, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '2 yogurt containers granulated sugar', 5, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '2 yogurt containers granulated sugar', 6, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '1 vanilla or plain yogurt, 170g container', 1, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '1 vanilla or plain yogurt, 170g container', 2, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '1 vanilla or plain yogurt, 170g container', 3, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '1 vanilla or plain yogurt, 170g container', 4, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '1 vanilla or plain yogurt, 170g container', 5, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '1 vanilla or plain yogurt, 170g container', 6, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, 'White flour', 1, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, 'White flour', 2, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, 'White flour', 3, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, 'White flour', 4, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, 'White flour', 5, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, 'White flour', 6, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '1.5 yogurt containers milk', 1, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '1.5 yogurt containers milk', 2, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '1.5 yogurt containers milk', 3, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '1.5 yogurt containers milk', 4, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '1.5 yogurt containers milk', 5, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '1.5 yogurt containers milk', 6, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '1/4 tsp cinnamon', 1, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '1/4 tsp cinnamon', 2, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '1/4 tsp cinnamon', 3, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '1/4 tsp cinnamon', 4, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '1/4 tsp cinnamon', 5, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '1/4 tsp cinnamon', 6, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '1 cup fresh blueberries ', 1, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '1 cup fresh blueberries ', 2, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '1 cup fresh blueberries ', 3, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '1 cup fresh blueberries ', 4, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '1 cup fresh blueberries ', 5, DEFAULT, null, null);
INSERT INTO ingredients ("id", "body", "recipe_id", "created_at", "updated_at", "deleted_at") VALUES (DEFAULT, '1 cup fresh blueberries ', 6, DEFAULT, null, null);