bind_addr = ":8001"
allowed_origins = "*"
log_level = "debug"
title = "Simple web site"
uploads = "web/uploads"
templates = "web/templates"


[database]
db_host = "blog_db"
db_port = "5432"
db_name = "site_db"
db_user = "web_user"
db_password = "password"
db_ssl = "disable"
migrations_dir = "migrations"

[cache]
host = "redis"
port = "6379"
password = ""
prefix = "app_"

[session]
key = "3373367639792442264528482B4D6251655468576D5A7134743777217A25432A462D4A404E635266556A586E3272357538782F413F4428472B4B625064536756"
name = "simple_web_site_session"
max_age = 604800
#session lifetime 1 week